### ISSUE TITLE
I can't connect the plugin to meilisearch

### ISSUE THREAD

**Issue by Druidblack** [arnesacnussem/jellyfin-plugin-meilisearch#1]
Good afternoon. Installed meilisearch

```
services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - /srv/config/meilisearch:/meili_data
    environment:
      MEILI_MASTER_KEY: "1234"
```

I write the address in the plugin http://192.168.1.161:7700
Meilisearch Api Key 1234

After saving, I get: meilisearch: Invalid URI: The URI scheme is not valid.

What am I doing wrong?

Jf: 10.10.1
